spring.jpa.hibernate.ddl-auto = update



management.endpoints.web.exposure.include=info,health
management.endpoint.info.enabled=true

#actuator properties
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details= always

